### ISSUE TITLE
Error slowing down script

### ISSUE THREAD

**Issue by elijahl197** [blissend/hqtrivia-automation#9]
Here is my error code let me know what I could be doing wrong please.
Elijahs-iMac:hq elijah$ python3 hqtrivia-automation.py -q
E1231 13:32:23.302100000 4320752448 ev_epollex_linux.cc:1482]          Skipping epollex becuase GRPC_LINUX_EPOLL is not defined.
E1231 13:32:23.302594000 4320752448 ev_epoll1_linux.cc:1261]           Skipping epoll1 becuase GRPC_LINUX_EPOLL is not defined.
E1231 13:32:23.302926000 4320752448 ev_epollsig_linux.cc:1761]         Skipping epollsig becuase GRPC_LINUX_EPOLL is not defined.
hqtrivia-automation.py: method - vision_ocr | raw - ['']
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "hqtrivia-automation.py", line 309, in vision_ocr
    self.raw.pop(-1) # swipe left comment
IndexError: pop from empty list
['wnere (IDES one 90 I0 961', 'tech support for an Apple', 'product?', 'Smart Pub', '"1\'11', 'Erudita Truck Stop', "7'9", '||', '-', '||']

hqtrivia-automation.py: Using Google Tesseract OCR

Question - wnere (IDES one 90 I0 961 tech support for an Apple product?

Choice - Smart Pub - Score 0
[Google]: 26 Oct 2016 ... Smart Pub Craiova organizeaza o diversitate de evenimente, incepand de la concerte si seri de teatru, pana la stan
[Keywords]: []

Choice - "1'11 - Score 0
[Google]: Aug 24, 2017 ... Have you been seeing the number 11 often? I am seeing 1:11 and 11:11 on the clock all the time. Eleven is the num
[Keywords]: []

Choice - Erudita Truck Stop - Score 0
[Google]: We're currently providing more than 45,000 The long term goal of the GTA SA: Liberty City mod is to recreate GTA III on the GTA Sa
[Keywords]: []

Choice - 7'9 - Score 0
[Keywords]: []

Choice - || - Score 0
[Keywords]: []

Choice - || - Score 0
[Keywords]: []

Answer - Smart Pub, "1'11, Erudita Truck Stop, 7'9, ||, || - highest score is 0

Total Time - 18.634683847427368

It seems to kinda work but the 18 seconds makes it unsuable during a game. Im using google cloud vision. Let me know what I am doing wrong. Note I'm using a picture of the question not used during a game so idk if that is causing errors. Thanks

**Comment by blissend** [comment]
Would you be able to send me the image or post on imgur for me? Looks like tesseract didn't read it right so I'm curious as to how the original image looks.

Also I just got back from long vacation and made many changes as of c26424e62f3bf2f39aa9cad1150dfcad5aaf0abe which is version 2018.01.11.04.30. So give it a try again and you'll notice it doesn't wait until all lookups on answers are complete. As soon as one lookup completes it starts displaying results that will get more accurate as more results come in (updates each time one comes in).
